In [1]:
import numpy as np
import pandas as pd
import random
import os
import json

<h2>Functions</h2>

<h3>General Functions</h3>

In [2]:
# Check if a Value is Nan
# param x - Value to check
# return boolean - If it is a Nan
def is_nan(x):
    return (x is np.nan or x != x)

# Check All Values in List are Nan
# param x - List to check
# return boolean - If it is all Nan
def list_is_nan(x):
    for i in x:
        if not is_nan(i): return False
    return True

# Converts names to single string
# param names (list) - List of names in the format [['Mia', 'Brown'],[..]]
# return unique (list) - List of names in the format ['Mia Brown', ..]
def name_to_str(names):
    return [",".join(name).replace(",", " ") for name in names]

# Converts names to single string
# param names (list) - List of names in the format ['Mia Brown', ..]
# return names_list (list) - List of names in the format [['Mia', 'Brown'],[..]]
def str_name_to_list(names):
    for i in range(len(names)):
        full_name = names[i].split()
        names[i] = [full_name[0], full_name[len(full_name) - 1]]
    return names

<h3>Get Unique Values</h3>

In [3]:
# Get the Names of Employees in the HR Dataset
# param df (dataframe) - Dataframe with names
# param column (str) - Column can be 'Employee Name' or 'Manager Name'
# Returns names (list) - Array of names (['First', 'Last'])
def get_names(df, column='Employee Name'):
    names = [df[[column]].iloc[i][0] for i in range(df.shape[0] - 1)]
    for i in range(len(names)):
        try:
            full_name = names[i].split(',')
            first = full_name[1].strip().split()[0]
            last = full_name[0]
            names[i] = [first, last]
        except:
            names[i] = ['Jeremy', 'Prater']
    return names

# Filter to list of unique names
# param names (list) - List of names in the format [['Mia', 'Brown'],[..]]
# param avoid (list) - List of names to avoid duplicates of
# return unique (list) - List of names in the format [['Mia', 'Brown'],[..]]
def filter_names_helper(names, avoid = []):
    unique = []
    first, last = [], []
    if(len(avoid) != 0):
        first = [n[0] for n in avoid]
        last = [n[1] for n in avoid]
    for name in names:
        if((name[0] not in first) and (name[1] not in last)):
            first.append(name[0])
            last.append(name[1])
            unique.append(name)
    return unique

# Filter to list of unique names that don't overlap with manager names
# param df (dataframe) - Dataframe with names 
# return unique (list) - List of names in the format [['Mia', 'Brown'],[..]]
def get_filtered_names(df):
    managers = str_name_to_list(get_uniq_str(df, "Manager Name"))
    managers = filter_names_helper(managers)
    survey_users = [['Mia','Brown'], ['Ivan','Rogers'], ['Julia','Soto'], ['Nan','Singh']]
    user_names = get_names(hr_data)
    user_names = filter_names_helper(user_names, avoid=survey_users)
    user_names = filter_names_helper(user_names, avoid=managers)
    user_names.extend(survey_users)
    return user_names

In [4]:
# Get the Unique Names of Employees in the HR Dataset
# param df (dataframe) - Dataframe with names
# return unique (list) - List of names in the format ['Mia Brown', ..]
def get_uniq_names(df):
    return filter_names(get_names(df))

# Get Unique String Values of a Dataframe Column
# param df (dataframe) - Source Dataframe
# param col_name (str) - Name of Column to get unique values'
# return uniq_arr (arr) - Array of Unique Values
def get_uniq_str(df, col_name):
    return [i.lower().strip() for i in df[col_name].unique()[:-1]]

# Get Unique String Values of a Dataframe Column
# param df (dataframe) - Source Dataframe
# param col_name (str) - Name of Column to get unique values'
# return uniq_arr (arr) - Array of Unique Values
def get_uniq_num(df, col_name):
    return [str(int(i)) for i in df[col_name].unique()[:-1]]

# Generate a Dictionary with Unique Values for Select Columns
# param df (dataframe) - Source Dataframe
# return uniq (dict) - Dictionary that maps entities to unique values
def gen_uniq_dict(df):
    # Get Unique Values of Relevant Columns
    uniq = {}
    # Predefined
    uniq['name'] = name_to_str(get_filtered_names(df))
    uniq['sex'] = ['male', 'female']
    uniq['employment_status'] = ['active', 'voluntarily terminated', 'terminated for a cause',
                          'on a leave of absence' + 'going to start work in the future']
    uniq['performance_score'] = ['fully meet performance expecations', 'are too early to review', 
                         'meet 90-day expectations', 'are exceptional', 'need improvement', 'exeed expecations']
    # Custom Preprocessing
    uniq['state'] = hr_data['State'].unique()[:-1]
    # Standard Preprocessing 
    uniq['age'] = get_uniq_num(hr_data, 'Age')
    uniq['maritaldesc'] = get_uniq_str(hr_data, "MaritalDesc")
    uniq['citizendesc'] = get_uniq_str(hr_data, "CitizenDesc")
    uniq['department'] = get_uniq_str(hr_data, "Department")
    uniq['position'] = get_uniq_str(hr_data, "Position")
    uniq['manager'] = name_to_str(str_name_to_list(get_uniq_str(hr_data, "Manager Name")))
    uniq['employee_source'] = get_uniq_str(hr_data, "Employee Source")
    return uniq

<h3>Load, Parse and Clean Entity Data</h3>

In [5]:
# Load entity data frame from CSV
# param path (str) - Path to csv
# return ent_df (dataframe) - Entity Info Dataframe
def load_ent(path):
    df = pd.read_csv(path).iloc[:, :4]
    ct = 0
    while (ct < len(df) and not list_is_nan(df.iloc[ct, :].values)): ct += 1
    return df.iloc[:ct, :]

# Parse CSV that contains [Entity, Options, Synonyms, Gazetteer]
# param ent_df (dataframe) - Contains the columns listed above
# return ent_dict (dict) - Uncleaned dictionary where the keys are the entities
#                          and the values are [options (arr), synonyms (arr), gazetteer (arr)]
def ent_parse(ent_df):
    ent_dict = {}
    ct = 0
    curr_ent = ''
    while(ct < len(ent_df)):
        row = ent_df.iloc[ct]
        # update curr_ent if new entity
        if(not is_nan(row['Entity'])): 
            curr_ent = row['Entity']
            ent_dict[curr_ent] = [[], [], []]
        # check if options is a list
        if(not is_nan(row['Options']) and row['Options'].count(',') > 2):
            ent_dict[curr_ent][0] = row['Options']
            if(not is_nan(row['Synonyms'])): 
                ent_dict[curr_ent][1] = row['Synonyms'].split(',')
            if(not is_nan(row[3])): ent_dict[curr_ent][2] = row['Gazetteer']
        # single entry in option column
        else:
            ent_dict[curr_ent][0].append(row['Options'])
            ent_dict[curr_ent][1].append(row['Synonyms'])
            ent_dict[curr_ent][2].append(row['Gazetteer'])
        ct += 1
    return ent_dict

# Cleans the gazetteers of the ent dictionary
# param ent_dict (dictionary) - Entity Dictionary
# return ent_dict (dictionary) - Cleaned Entity Dictionary
def clean_options(ent_dict):
    for i in ent_dict.keys():
        old_opt = ent_dict[i][0]
        new_opt = []
        for word in old_opt:
            if(not is_nan(word)):
                new_opt.append(word.replace("'", "").replace(",", ""))
        ent_dict[i][0] = new_opt
    return ent_dict

# Cleans the gazetteers of the ent dictionary
# param ent_dict (dictionary) - Entity Dictionary
# return ent_dict (dictionary) - Cleaned Entity Dictionary
def clean_synonyms(ent_dict):
    for i in ent_dict.keys():
        old_syn = ent_dict[i][1]
        new_syn = []
        if(len(old_syn) != 0):
            for j in old_syn:
                if(not is_nan(j)): new_syn.append([string.strip() for string in j.split(',')])
                else: new_syn.append(j)
        ent_dict[i][1] = new_syn
    return ent_dict

# Cleans the gazetteers of the ent dictionary
# param ent_dict (dictionary) - Entity Dictionary
# return ent_dict (dictionary) - Cleaned Entity Dictionary
def clean_gazetteer(ent_dict):
    for i in ent_dict.keys():
        old_gaz = ent_dict[i][2]
        clean_gaz = []
        if (len(old_gaz) != 0):        
            if (type(old_gaz) is str): clean_gaz = old_gaz.split(',')
            elif(not is_nan(old_gaz[0])): clean_gaz = (old_gaz[0].split(','))
        ent_dict[i][2] = [i.strip() for i in clean_gaz]
    return ent_dict

# Cleans an Entity Dictionary
# ent_dict (dict) - Uncleaned dictionary of parsed entity information
# uniq (dict) - Dictionary that maps entities to unique values
# return cleaned_ent_dict (dict) - Cleaned dictionary
def clean_ent_dict(ent_dict, uniq):
    ent_dict = clean_options(ent_dict)
    ent_dict = clean_synonyms(ent_dict)
    ent_dict = clean_gazetteer(ent_dict)
    ent_dict['name'][0] = uniq['name']
    ent_dict['state'][0] = uniq['state']
    ent_dict['age'][0] = uniq['age']
    ent_dict['manager'][0] = uniq['manager']
    return ent_dict

# Parse and Clean Entity Data
# Parse CSV that contains [Entity, Options, Synonyms, Gazetteer]
# param ent_df (dataframe) - Contains the columns listed above
def parse_clean_ent(ent_df, uniq):
    ent = ent_parse(ent_df)
    return clean_ent_dict(ent, uniq)

<h3>File Generation</h3>

In [50]:
# Convert a list into a text file
# param folder (str) - Name of the folder to write the file
# param lines (list) - List of values to write to file
def list_to_txt_file(folder, lines):
    directory = '../hr_assistant/entities/' + folder + '/'
    if not os.path.exists(directory): os.makedirs(directory)
    with open(directory + 'gazetteer.txt', 'w+') as filehandle:  
        filehandle.writelines("%s\n" % line for line in lines)
        
# Convert a dict into a json file
# param folder (str) - Name of the folder to write the file
# param dict (dict) - Json dict to write to file
def dict_to_json_file(folder, json_dict):
    directory = '../hr_assistant/entities/' + folder + '/'
    if not os.path.exists(directory): os.makedirs(directory)
    with open(directory + "mapping.json", "w+") as f:
        json_str = json.dumps(json_dict, indent=4)
        f.write(json_str)
        
# Generate a Mapping JSON Dict to create Mapping.json file
# param ent_dict (dict) - Dictionary that maps entities to options, synonyms, and gazetteer
# param entity (str) - The entity to generate the gazetteer list for
# return json_dict (dict) - Json Dict in the proper format for mapping.json
def gen_map_json(ent_dict, entity):
    opt = ent_dict[entity][0]
    syn = ent_dict[entity][1]
    # Check if the Options and the Synonyms Align
    if(len(opt) != len(syn)): syn = [[] for i in range(len(opt))]
    return gen_map_json_helper(opt, syn)

# Helper function to Generate a Mapping JSON Dictionary
# param options (list) - Array of options
# param synonyms (2d list) - Array of synonym arrays corresponding to options
# return json_dict (dict) - Json Dict in the proper format for mapping.json
def gen_map_json_helper(options, synonyms):
    json_dict = {}
    json_dict['entities'] = []
    for i in range(len(options)):
        new_dict = {}
        if(is_nan(synonyms[i])): new_dict['whitelist'] = []
        else: new_dict['whitelist'] = synonyms[i]
        new_dict['cname'] = options[i]
        json_dict['entities'].append(new_dict)
    return json_dict

# Create Mapping.json files for Every Entity in an Entity Dictionary
# param ent_dict (dict) - Dictionary that maps entities to options, synonyms, and gazetteer
def gen_map_json_files(ent_dict):
    for entity in ent_dict.keys():
        json_dict = gen_map_json(ent_dict, entity)
        if(not is_nan(json_dict)): dict_to_json_file(entity, json_dict)

# Collect All Synonyms for a Single Entity in Entity Dict
# param ent_dict (dict) - Dictionary that maps entities to options, synonyms, and gazetteer
# param entity (str) - The entity to get Synyonyms for
# return synonyms (list) - List of Synonyms of Specified entity
def get_synonyms(ent_dict, entity):
    synonyms = []
    for syn in ent_dict[entity][1]:
        if(not is_nan(syn)): synonyms.extend(syn)
    return synonyms

# Generate a Gazetter List for an Entity
# param ent_dict (dict) - Dictionary that maps entities to options, synonyms, and gazetteer
# param entity (str) - The entity to generate the gazetteer list for
# return gaz (list) - List of gazetteer word relevant to the entity
def gen_gaz_list(ent_dict, entity):
    gaz = []
    gaz.extend(ent_dict[entity][0])
    gaz.extend(get_synonyms(ent_dict, entity))
    gaz.extend(ent_dict[entity][2])
    return gaz

# Create Gazetteer Files for Every Entity in an Entity Dictionary
# param ent_dict (dict) - Dictionary that maps entities to options, synonyms, and gazetteer
def gen_gazetteers(ent_dict):
    for entity in ent_dict.keys():
        gaz_list = gen_gaz_list(ent_dict, entity)
        list_to_txt_file(entity, gaz_list)

<h2>Workflow</h2>

<h4>Load Data</h4>

In [9]:
hr_data = pd.read_csv('old_core_dataset.csv')
hr_data

,Employee Name,Employee Number,State,Zip,DOB,Age,Sex,MaritalDesc,CitizenDesc,Hispanic/Latino,...,Date of Hire,Date of Termination,Reason For Term,Employment Status,Department,Position,Pay Rate,Manager Name,Employee Source,Performance Score
0,"Brown, Mia",1.103024e+09,MA,1450.0,11/24/1985,32.0,Female,Married,US Citizen,No,...,10/27/2008,NaN,N/A - still employed,Active,Admin Offices,Accountant I,28.50,Brandon R. LeBlanc,Diversity Job Fair,Fully Meets
1,"LaRotonda, William",1.106027e+09,MA,1460.0,4/26/1984,33.0,Male,Divorced,US Citizen,No,...,1/6/2014,NaN,N/A - still employed,Active,Admin Offices,Accountant I,23.00,Brandon R. LeBlanc,Website Banner Ads,Fully Meets
2,"Steans, Tyrone",1.302053e+09,MA,2703.0,9/1/1986,31.0,Male,Single,US Citizen,No,...,9/29/2014,NaN,N/A - still employed,Active,Admin Offices,Accountant I,29.00,Brandon R. LeBlanc,Internet Search,Fully Meets
3,"Howard, Estelle",1.211051e+09,MA,2170.0,9/16/1985,32.0,Female,Married,US Citizen,No,...,2/16/2015,4/15/2015,N/A - still employed,Active,Admin Offices,Administrative Assistant,21.50,Brandon R. LeBlanc,Pay Per Click - Google,N/A- too early to review
4,"Singh, Nan",1.307060e+09,MA,2330.0,5/19/1988,29.0,Female,Single,US Citizen,No,...,5/1/2015,NaN,N/A - still employed,Active,Admin Offices,Administrative Assistant,16.56,Brandon R. LeBlanc,Website Banner Ads,N/A- too early to review
5,"Smith, Leigh Ann",7.110077e+08,MA,1844.0,6/14/1987,30.0,Female,Married,US Citizen,No,...,9/26/2011,9/25/2013,career change,Voluntarily Terminated,Admin Offices,Administrative Assistant,20.50,Brandon R. LeBlanc,Diversity Job Fair,Fully Meets
6,"LeBlanc, Brandon R",1.102024e+09,MA,1460.0,6/10/1984,33.0,Male,Married,US Citizen,No,...,1/5/2016,NaN,N/A - still employed,Active,Admin Offices,Shared Services Manager,55.00,Janet King,Monster.com,Fully Meets
7,"Quinn, Sean",1.206043e+09,MA,2045.0,11/6/1984,33.0,Male,Married,Eligible NonCitizen,No,...,2/21/2011,8/15/2015,career change,Voluntarily Terminated,Admin Offices,Shared Services Manager,55.00,Janet King,Diversity Job Fair,Fully Meets
8,"Boutwell, Bonalyn",1.307060e+09,MA,2468.0,4/4/1987,30.0,Female,Married,US Citizen,No,...,2/16/2015,NaN,N/A - still employed,Active,Admin Offices,Sr. Accountant,34.95,Brandon R. LeBlanc,Diversity Job Fair,90-day meets
9,"Foster-Baker, Amy",1.201031e+09,MA,2050.0,4/16/1979,38.0,Female,Married,US Citizen,no,...,1/5/2009,NaN,N/A - still employed,Active,Admin Offices,Sr. Accountant,34.95,Board of Directors,Other,Fully Meets
10,"King, Janet",1.001495e+09,MA,1902.0,9/21/1954,63.0,Female,Married,US Citizen,Yes,...,7/2/2012,NaN,N/A - still employed,Active,Executive Office,President & CEO,80.00,Board of Directors,Pay Per Click - Google,Fully Meets
11,"Zamora, Jennifer",1.112031e+09,MA,2067.0,8/30/1979,38.0,Female,Single,US Citizen,No,...,4/10/2010,NaN,N/A - still employed,Active,IT/IS,CIO,65.00,Janet King,Employee Referral,Exceptional
12,"Becker, Renee",1.102024e+09,MA,2026.0,4/4/1986,31.0,Female,Single,US Citizen,Yes,...,7/7/2014,9/12/2015,performance,Terminated for Cause,IT/IS,Database Administrator,43.00,Simon Roup,Search Engine - Google Bing Yahoo,Fully Meets
13,"Goble, Taisha",9.050137e+08,MA,2127.0,10/23/1971,46.0,Female,Single,US Citizen,No,...,2/16/2015,3/15/2015,"no-call, no-show",Terminated for Cause,IT/IS,Database Administrator,48.50,Simon Roup,Glassdoor,Fully Meets
14,"Hernandez, Daniff",1.410071e+09,MA,1960.0,8/7/1986,31.0,Male,Married,US Citizen,No,...,2/16/2015,2/22/2015,"no-call, no-show",Terminated for Cause,IT/IS,Database Administrator,40.10,Simon Roup,Employee Referral,N/A- too early to review
15,"Horton, Jayne",1.105026e+09,MA,2493.0,2/21/1984,33.0,Female,Single,US Citizen,No,...,3/30/2015,NaN,N/A - still employed,Active,IT/IS,Database Administrator,34.00,Simon Roup,Glassdoor,N/A- too early to review
16,"Johnson, Noelle",1.003018e+09,MA,2301.0,11/7/1986,31.0,Female,Married,US Citizen,No,...,1/5/2015,NaN,N/A - still employed,Leave of Absence,IT/IS,Database Administrator,40.00,Simon Roup,Glassdoor,90-day meets
17,"Murray, Thomas",1.406068e+09,TX,78230.0,7/4/1988,29.0,Male,Divorced,US Citizen,No,...,11/10/2014,NaN,N/A - still employed,Active,IT/IS,Database Administrator,35.50,Simon Roup,Diversity Job Fair,Exceptional
18,"Pearson, Randall",1.102024e+09,MA,2747.0,9/5/1984,33.0,Male,Married,US Citizen,No,...,12/1/2014,5/1/2016,performance,Voluntarily Terminated,IT/IS,Database Administrator,41.00,Simon Roup,Employee Referral,Fully Meets
19,"Petrowsky, Thelma",1.108028e+09,MA,1886.0,9/16/1984,33.0,Female,Married,US Citizen,No,...,11/10/2014,NaN,N/A - still employed,Active,IT/IS,Database Administrator,42.75,Simon Roup,Employee Referral,Exceptional
20,"Roby, Lori",1.407069e+09,MA,1886.0,10/11/1981,36.0,Female,Married,US Citizen,No,...,2/16/2015,NaN,N/A - still employed,Active,IT/IS,Database Administrator,39.55,Simon Roup,Employee Referral,Fully Meets
21,"Rogers, Ivan",1.203032e+09,MA,1810.0,8/26/1986,31.0,Male,Married,US Citizen,No,...,3/30/2015,NaN,N/A - still employed,Active,IT/IS,Database Administrator,42.20,Simon Roup,Pay Per Click - Google,N/A- too early to review
22,"Salter, Jason",1.111030e+09,MA,2452.0,12/17/1987,30.0,Male,Divorced,US Citizen,No,...,1/5/2015,10/31/2015,hours,Voluntarily Terminated,IT/IS,Database Administrator,45.00,Simon Roup,Vendor Referral,90-day meets
23,"Simard, Kramer",8.080103e+08,MA,2110.0,2/8/1970,47.0,Male,Married,US Citizen,Yes,...,1/5/2015,NaN,N/A - still employed,Active,IT/IS,Database Administrator,30.20,Simon Roup,Employee Referral,90-day meets
24,"Zhou, Julia",1.110030e+09,MA,2148.0,2/24/1979,38.0,Female,Single,US Citizen,No,...,3/30/2015,NaN,N/A - still employed,Active,IT/IS,Database Administrator,31.40,Simon Roup,Employee Referral,90-day meets
25,"Foss, Jason",1.192991e+09,MA,1460.0,7/5/1980,37.0,Male,Single,US Citizen,No,...,4/15/2011,NaN,N/A - still employed,Active,IT/IS,IT Director,65.00,Jennifer Zamora,Professional Society,Exceptional
26,"Roup,Simon",1.106027e+09,MA,2481.0,4/5/1973,44.0,Male,Single,US Citizen,No,...,1/20/2013,NaN,N/A - still employed,Active,IT/IS,IT Manager - DB,62.00,Jennifer Zamora,Professional Society,Fully Meets
27,"Ruiz, Ricardo",1.001175e+09,MA,1915.0,1/4/1964,54.0,Male,Divorced,US Citizen,No,...,1/9/2012,11/4/2015,hours,Voluntarily Terminated,IT/IS,IT Manager - DB,21.00,Jennifer Zamora,Diversity Job Fair,Fully Meets
28,"Monroe, Peter",1.011023e+09,MA,2134.0,10/5/1986,31.0,Male,Married,Eligible NonCitizen,Yes,...,2/15/2012,NaN,N/A - still employed,Active,IT/IS,IT Manager - Infra,63.00,Jennifer Zamora,Diversity Job Fair,Needs Improvement
29,"Dougall, Eric",1.101024e+09,MA,1886.0,7/9/1970,47.0,Male,Single,US Citizen,No,...,1/5/2014,NaN,N/A - still employed,Active,IT/IS,IT Manager - Support,64.00,Jennifer Zamora,Professional Society,Exceeds
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272,Jeremy Prater,1.001085e+09,NV,89139.0,5/9/1974,43.0,Male,Married,US Citizen,No,...,5/12/2014,NaN,N/A - still employed,Active,Sales,Area Sales Manager,56.00,Lynn Daneault,Website Banner Ads,PIP
273,"Khemmich, Bartholemew",1.104025e+09,CO,80820.0,11/27/1979,38.0,Male,Single,US Citizen,No,...,8/19/2013,NaN,N/A - still employed,Active,Sales,Area Sales Manager,55.00,Lynn Daneault,Pay Per Click - Google,Fully Meets
274,"Leruth, Giovanni",1.412072e+09,UT,84111.0,12/27/1988,29.0,Male,Separated,US Citizen,No,...,4/30/2012,NaN,N/A - still employed,Active,Sales,Area Sales Manager,55.00,John Smith,Website Banner Ads,Fully Meets
275,"Martins, Joseph",1.209049e+09,TX,78207.0,6/11/1970,47.0,Male,Single,Eligible NonCitizen,No,...,5/14/2012,NaN,N/A - still employed,Active,Sales,Area Sales Manager,56.00,Lynn Daneault,Employee Referral,Fully Meets
276,"McKinzie, Jac",1.209049e+09,TX,78789.0,7/1/1984,33.0,Male,Married,US Citizen,No,...,7/6/2016,NaN,N/A - Has not started yet,Future Start,Sales,Area Sales Manager,55.00,Lynn Daneault,Website Banner Ads,N/A- too early to review
277,"Mullaney, Howard",1.306058e+09,AL,36006.0,11/2/1975,42.0,Male,Single,US Citizen,No,...,9/29/2014,NaN,N/A - still employed,Active,Sales,Area Sales Manager,55.00,John Smith,Internet Search,Needs Improvement
278,"Nguyen, Dheepa",1.111031e+09,GA,30428.0,3/31/1989,28.0,Female,Single,US Citizen,No,...,7/8/2013,NaN,N/A - still employed,Active,Sales,Area Sales Manager,55.00,Lynn Daneault,Pay Per Click - Google,Fully Meets
279,"Onque, Jasmine",1.501072e+09,FL,33174.0,5/11/1990,27.0,Female,Single,US Citizen,Yes,...,9/30/2013,NaN,N/A - still employed,Active,Sales,Area Sales Manager,57.00,Lynn Daneault,Pay Per Click - Google,Fully Meets
280,"Ozark, Travis",8.120118e+08,NC,27229.0,5/19/1982,35.0,Male,Single,US Citizen,No,...,1/5/2015,NaN,N/A - still employed,Active,Sales,Area Sales Manager,55.00,John Smith,Website Banner Ads,90-day meets
281,"Potts, Xana",1.102024e+09,KY,40220.0,8/29/1988,29.0,Female,Married,US Citizen,No,...,1/9/2012,NaN,N/A - still employed,Active,Sales,Area Sales Manager,55.00,Lynn Daneault,Website Banner Ads,Fully Meets
282,"Riordan, Michael",1.502073e+09,ND,58782.0,1/15/1968,50.0,Male,Separated,US Citizen,No,...,1/9/2006,NaN,N/A - still employed,Active,Sales,Area Sales Manager,55.00,Lynn Daneault,Billboard,Exceeds
283,"Strong, Caitrin",1.411071e+09,MT,59102.0,5/12/1989,28.0,Female,Married,US Citizen,No,...,9/27/2010,NaN,N/A - still employed,Active,Sales,Area Sales Manager,54.00,John Smith,Professional Society,Fully Meets
284,"Terry, Sharlene",1.401065e+09,OR,97756.0,5/7/1965,52.0,Female,Single,US Citizen,No,...,9/29/2014,NaN,N/A - still employed,Active,Sales,Area Sales Manager,55.00,Lynn Daneault,Monster.com,Fully Meets
285,"Valentin,Jackie",1.312064e+09,AZ,85006.0,5/23/1991,26.0,Female,Married,US Citizen,No,...,7/5/2011,NaN,N/A - still employed,Active,Sales,Area Sales Manager,55.00,John Smith,Other,Fully Meets
286,"Villanueva, Noah",1.111031e+09,ME,4063.0,7/11/1989,28.0,Male,Single,US Citizen,No,...,3/5/2012,NaN,N/A - still employed,Active,Sales,Area Sales Manager,56.00,John Smith,Website Banner Ads,Fully Meets
287,"Houlihan, Debra",1.009022e+09,RI,2908.0,3/17/1966,51.0,Female,Married,US Citizen,No,...,5/5/2014,NaN,N/A - still employed,Active,Sales,Director of Sales,60.00,Janet King,MBTA ads,Fully Meets
288,"Daneault, Lynn",1.402065e+09,VT,5473.0,4/19/1990,27.0,Female,Single,US Citizen,No,...,5/5/2014,NaN,N/A - still employed,Active,Sales,Sales Manager,54.00,Debra Houlihan,Pay Per Click - Google,Fully Meets
289,"Kampew, Donysha",1.109029e+09,PA,19444.0,11/11/1989,28.0,Female,Single,US Citizen,No,...,11/7/2011,4/24/2014,maternity leave - did not return,Voluntarily Terminated,Sales,Sales Manager,60.25,Debra Houlihan,Social Networks - Facebook Twitter etc,Fully Meets
290,"Smith, John",1.499903e+09,MA,1886.0,8/16/1984,33.0,Male,Divorced,US Citizen,no,...,5/18/2014,NaN,N/A - still employed,Active,Sales,Sales Manager,56.00,Debra Houlihan,Diversity Job Fair,Needs Improvement
291,"Andreola, Colby",1.107027e+09,MA,2110.0,5/24/1979,38.0,Female,Single,US Citizen,No,...,11/10/2014,NaN,N/A - still employed,Active,Software Engineering,Software Engineer,47.60,Alex Sweetwater,Vendor Referral,Fully Meets
292,"Carabbio, Judith",1.101024e+09,MA,2132.0,4/5/1987,30.0,Female,Single,US Citizen,No,...,11/11/2013,NaN,N/A - still employed,Active,Software Engineering,Software Engineer,56.00,Alex Sweetwater,Pay Per Click - Google,90-day meets
293,"Del Bosque, Keyla",1.203032e+09,MA,2176.0,7/5/1979,38.0,Female,Single,US Citizen,No,...,1/9/2012,NaN,N/A - still employed,Active,Software Engineering,Software Engineer,57.12,Alex Sweetwater,Monster.com,90-day meets
294,"Exantus, Susan",1.401065e+09,MA,1749.0,5/15/1987,30.0,Female,Married,US Citizen,No,...,5/2/2011,6/5/2013,attendance,Terminated for Cause,Software Engineering,Software Engineer,48.50,Alex Sweetwater,Billboard,Needs Improvement
295,"Martin, Sandra",1.303055e+09,MA,2135.0,11/7/1987,30.0,Female,Separated,US Citizen,No,...,11/11/2013,NaN,N/A - still employed,Active,Software Engineering,Software Engineer,55.51,Alex Sweetwater,Search Engine - Google Bing Yahoo,Fully Meets
296,"Patronick, Luke",1.112031e+09,MA,1844.0,2/20/1979,38.0,Male,Single,US Citizen,No,...,11/7/2011,9/7/2015,Another position,Voluntarily Terminated,Software Engineering,Software Engineer,52.25,Alex Sweetwater,Diversity Job Fair,Exceeds
297,"Saada, Adell",1.012023e+09,MA,2132.0,7/24/1986,31.0,Female,Married,US Citizen,No,...,11/5/2012,NaN,N/A - still employed,Active,Software Engineering,Software Engineer,49.25,Alex Sweetwater,Pay Per Click - Google,Fully Meets
298,"Szabo, Andrew",1.201031e+09,MA,2140.0,5/6/1983,34.0,Male,Single,US Citizen,No,...,7/7/2014,NaN,N/A - still employed,Active,Software Engineering,Software Engineer,48.00,Alex Sweetwater,MBTA ads,Exceptional
299,"True, Edward",1.102024e+09,MA,2451.0,6/14/1983,34.0,Male,Single,Non-Citizen,No,...,2/18/2013,4/15/2014,medical issues,Voluntarily Terminated,Software Engineering,Software Engineer,45.42,Alex Sweetwater,Diversity Job Fair,Fully Meets
300,"Sweetwater, Alex",1.001645e+09,MA,2184.0,11/22/1966,51.0,Male,Single,US Citizen,No,...,8/15/2011,NaN,N/A - still employed,Active,Software Engineering,Software Engineering Manager,27.00,Jennifer Zamora,Search Engine - Google Bing Yahoo,Fully Meets
301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<h4>Create Unique Values Dictionary</h4>

In [10]:
uniq = gen_uniq_dict(hr_data)

<h4>Load Entities</h4>

In [11]:
ent_df = load_ent('HR Manager Schema - Entities.csv')
ent_df

,Entity,Options,Synonyms,Gazetteer
0,name,NaN,NaN,NaN
1,state,"MA', 'TX', 'CT', 'VA', 'VT', 'CA', 'WA', 'NH',...","Massachussets, Texas, Connecticut, Virginia, V...","state, state of birth, state of residence, off..."
2,age,age,"old, years old, age of, ages of",NaN
3,sex,male,"men, males, guys, dudes, gents, gentlemen, boys","sex, gender, masculine, feminine, male person"
4,NaN,female,"women, females, ladies, lady, ladys, girls, ga...",NaN
5,maritaldesc,married,"wed, legally married, espoused, joined in holy...","husbandless, without a partner, unwedded, wife..."
6,NaN,divorced,NaN,NaN
7,NaN,single,"unmarried, bachelor, bachelorette",NaN
8,NaN,separated,NaN,NaN
9,NaN,widowed,NaN,NaN
10,citizendesc,us citizen,NaN,"immigrant, illegal immigrant, h1 visa, foreign..."
11,NaN,eligible noncitizen,NaN,NaN
12,NaN,non-citizen,NaN,NaN
13,racedesc,black or african american,"black, african american, african-american","ethnicity, race, racial background, ethnic gro..."
14,NaN,asian,from asia,NaN
15,NaN,two or more races,"multiracial, multi-racial, mixed, mixed race, ...",NaN
16,NaN,"white',",caucasian,NaN
17,NaN,"hispanic',",latino,NaN
18,NaN,american indian or alaska native',"native, natives, indians, indian, american ind...",NaN
19,reason_for_termination,"return to school',","went back to school, had to go to school again...",NaN
20,NaN,"another position',","took on another job, landed a new position, ch...",NaN
21,NaN,"unhappy',","wasn't happy, didn't like his job, didn't like...",NaN
22,NaN,"military',","joined the military, went to the military, lef...",NaN
23,NaN,"gross misconduct',",NaN,NaN
24,NaN,"hours',",NaN,NaN
25,NaN,"medical issues',","got sick, fell sick, medical problems, sick",NaN
26,NaN,"relocation out of area',","was relocated, had to relocated, was assigned ...",NaN
27,NaN,"more money',",NaN,NaN
28,NaN,"career change',",changed careers,NaN
29,NaN,"n/a - has not started yet',",NaN,NaN
...,...,...,...,...
84,NaN,"careerbuilder',",NaN,NaN
85,NaN,"mbta ads',","advertisement, ads",NaN
86,NaN,"word of mouth',",verbal mention,NaN
87,NaN,"other',",NaN,NaN
88,NaN,"vendor referral',","referred by vendor, vendor referred",NaN
89,NaN,"on-campus recruiting',","on-campus job fair, career fair",NaN
90,NaN,"website banner ads',",NaN,NaN
91,NaN,"employee referral',",referred by employee,NaN
92,performance_score,"exceptional',",extraordinary,"performance rating, performance score"
93,NaN,"fully meets',","up to the mark, meet expectations",NaN
94,NaN,"n/a- too early to review',",NaN,NaN
95,NaN,"pip',",NaN,NaN
96,NaN,"needs improvement',",NaN,NaN
97,NaN,"exceeds',","beyond expectations, more than expected, bette...",NaN
98,NaN,90-day meets',NaN,NaN
99,money,pay rate,"salary, income, pay, earn, earnings, make, dol...","earns, makes, amount"
100,comparator,more than,"greater than, higher than, longer, over, older...",NaN
101,NaN,equals to,"is exactly, is equal to, equates to",NaN
102,NaN,less than,"lower than, below, under, fewer than",NaN
103,date_time,"date of hire',","start date, date of starting employment, hirin...",year
104,NaN,"date of termination',","end date, date of leaving job, date of ending ...",NaN
105,NaN,"dob',","birthday, birthdate, birth date, date of birth...",NaN
106,time_interval,time_interval,"yearly, monthly, annually, bi-weekly, hourly, ...","00's, 10's, 20's, 30's, 40's, 50's, 60's, 70's..."
107,function,percent,"fraction, portion, proportion, percentage, %","distribution, turn over rate, pct"
108,NaN,sum,"total, cumulative, added up, summed up. totall...",NaN
109,NaN,average,"mean, typical, typically",NaN
110,extreme,highest,"top, maximum, most, greatest, max",NaN
111,NaN,lowest,"least, minimum, bottom, lowest, min",NaN
112,employment_action,hired,"employed, recruited",joined
113,NaN,terminated,"fired, let go",NaN

In [12]:
ent_dict = parse_clean_ent(ent_df, uniq)
ent_dict

{'name': [['William LaRotonda',
   'Tyrone Steans',
   'Estelle Howard',
   'Leigh Smith',
   'Brandon LeBlanc',
   'Sean Quinn',
   'Bonalyn Boutwell',
   'Amy Foster-Baker',
   'Janet King',
   'Jennifer Zamora',
   'Renee Becker',
   'Taisha Goble',
   'Daniff Hernandez',
   'Jayne Horton',
   'Noelle Johnson',
   'Thomas Murray',
   'Randall Pearson',
   'Thelma Petrowsky',
   'Lori Roby',
   'Jason Salter',
   'Kramer Simard',
   'Simon Roup',
   'Ricardo Ruiz',
   'Peter Monroe',
   'Eric Dougall',
   'Rick Clayton',
   'Lisa Galia',
   'Leonara Lindsay',
   'Alejandro Bacong',
   'Anthony Cisco',
   'Linda Dolan',
   'Maria Gonzalez',
   'Carlos Merlos',
   'Tanya Morway',
   'Anita Shepard',
   'Neville Tredinnick',
   'Jumil Turpin',
   'Karthikeyan Ait Sidi',
   'Claudia Carr',
   'Donald Favis',
   'Bianca Roehrich',
   'Ann Daniele',
   'Jyoti Lajiri',
   'Jeremiah Semizoglou',
   'Joe South',
   'Sarah Warfield',
   'Elisa Bramante',
   'Michael Albert',
   'Charles Bozzi',
   'Webster Butler',
   'Elijiah Gray',
   'Jonathan Hogland',
   'Walter Immediato',
   'Ketsia Liebig',
   'Brannon Miller',
   'Ebonee Peterson',
   'Kelley Spirea',
   'David Stanley',
   'Kissy Sullivan',
   'Courtney Wallace',
   'Wilson Adinolfi',
   'Trina Alagbe',
   'Carol Anderson',
   'Sam Athwal',
   'Rachael Baczenski',
   'Francesco Barone',
   'Nader Barton',
   'Lowan Biden',
   'Helen Billis',
   'Donna Brill',
   'Josephine Bugali',
   'Beatrice Chace',
   'Lin Chan',
   'Donovan Chang',
   'Enola Chivukula',
   'Caroline Cierpiszewski',
   'Elijian Clukey',
   'James Cockel',
   'Spencer Cole',
   'Jean Crimmings',
   "Jene'ya Darson",
   'Carl Desimone',
   'Geoff Dickinson',
   'Lily DiNocco',
   'Denisa Dobrin',
   'Marianne Eaton',
   'Rex England',
   'Miguel Estremera',
   'April Evensen',
   'Susan Ferguson',
   'Nilson Fernandes',
   'Violeta Ferreira',
   'Libby Fidelia',
   'Raul Garcia',
   'Hamish Garneau',
   'Barbara Gaul',
   'Mildred Gentry',
   'Melisa Gerke',
   'Alex Gilles',
   'Evelyn Girifalco',
   'Shenice Gold',
   'Roxana Goyal',
   'Paula Gross',
   'Joanne Handschiegl',
   'Ludwick Harrell',
   'Christie Harrington',
   'Kara Harrison',
   'Rose Ivey',
   'Maryellen Jackson',
   'Hannah Jacobi',
   'Sneha Jhaveri',
   'Judy Jung',
   'Kathleen Kinsella',
   'Alexandra Kirill',
   'Bradley Knapp',
   'John Kretschmer',
   'Enrico Langton',
   'Dallas Leach',
   'Marilyn Linares',
   'Allison Lydon',
   'Lindsay Lynch',
   'Samuel MacLennan',
   'Lauren Mahoney',
   'Debbie Mangal',
   'Shana Maurice',
   'Sandy Mckenna',
   'Elizabeth Meads',
   'Dawn Motlagh',
   'Colombui Ndzi',
   'Richard Newman',
   'Shari Ngodup',
   'Lei-Ming Nguyen',
   "Lynn O'hare",
   'Adeel Osturnka',
   'Clinton Owad',
   'Nina Panjwani',
   'Emil Pelech',
   'Shakira Perry',
   'Hong Pham',
   'Brad Pitt',
   'Morissa Power',
   'Louis Punjabhi',
   'Janine Purinton',
   'Quinn Rarrick',
   'Haley Rivera',
   'Alain Robinson',
   'Ashley Rose',
   'Bruno Rossetti',
   'Melinda Saar-Beckles',
   'Nore Sadki',
   'Kamrin Sander',
   'Nori Sewkumar',
   'Seffi Shields',
   'Taylor Sparks',
   'Kristen Squatrito',
   'Desiree Tavares',
   'Sophia Theamstern',
   'Theresa Tinto',
   'Jeanette Tippett',
   'Mei Trang',
   'Abdellah Veera',
   'Colleen Volk',
   'Anna Von Massenbach',
   'Scott Whittier',
   'Barry Wilber',
   'Jacquelyn Williams',
   'Catherine Ybarra',
   'Kimberly Beak',
   'Dianna Blount',
   'Betsy Bondwell',
   'Joseph Buccheri',
   'Joelle Burke',
   'Benjamin Burkett',
   'Phil Close',
   'Daniel Davis',
   'Carla Demita',
   'Angela Erilus',
   'Megan Faller',
   'Nicole Fancett',
   'Phylicia Gosciminski',
   'Earnest Hankard',
   'Adrienne Homberger',
   'Julissa Hunts',
   'Rosalie Hutter',
   'Ming Huynh',
   'Tayana Jeannite',
   'Yen Johnston',
   'Lindsey Langford',
   'Mohammed Latif',
   'Mathew Linden',
   'Robyn Manchester',
   'Karen Mancuso',
   'Brigit McCarthy',
   'Erasumus Monkfish',
   'Luisa Monterro',
   'Patrick Moran',
   'Maliki Moumanil',
   'Kristie Nowlan',
   'Brooke Oliver',
   'Ermine Pelletier',
   'May Roberson',
   'Adil Sahoo',
   'Constance Sloan',
   'Lenora Tejeda',
   'Kenneth Thibaud',
   'Cybil Trzeciak',
   'Roger Walker',
   'Jordan Winthrop',
   'Hang Wolk',
   'Edward Buck',
   'Jessica Bunbury',
   'Michelle Carter',
   'Latia Costa',
   'Jenna Dietrich',
   'Alfred Digitale',
   'Maruk Fraval',
   'Gerry Friedman',
   'Whitney Gill',
   'Myriam Givens',
   'Mike Guilianno',
   'Jeremy Prater',
   'Bartholemew Khemmich',
   'Giovanni Leruth',
   'Jac McKinzie',
   'Howard Mullaney',
   'Jasmine Onque',
   'Travis Ozark',
   'Xana Potts',
   'Caitrin Strong',
   'Sharlene Terry',
   'Jackie Valentin',
   'Noah Villanueva',
   'Debra Houlihan',
   'Donysha Kampew',
   'Colby Andreola',
   'Judith Carabbio',
   'Keyla Del Bosque',
   'Sandra Martin',
   'Luke Patronick',
   'Adell Saada',
   'Andrew Szabo',
   'Mia Brown',
   'Ivan Rogers',
   'Julia Soto',
   'Nan Singh'],
  [nan],
  []],
 'state': [array(['MA', 'TX', 'CT', 'VA', 'VT', 'CA', 'WA', 'NH', 'NY', 'OH', 'IN',
         'ID', 'TN', 'NV', 'CO', 'UT', 'AL', 'GA', 'FL', 'NC', 'KY', 'ND',
         'MT', 'OR', 'AZ', 'ME', 'RI', 'PA'], dtype=object),
  [['Massachussets'],
   ['Texas'],
   ['Connecticut'],
   ['Virginia'],
   ['Vermony'],
   ['California'],
   ['Washington'],
   ['New Hampshire'],
   ['New York'],
   ['Ohio'],
   ['Indiana'],
   ['Idaho'],
   ['Tennessee'],
   ['Nevada'],
   ['Colarado'],
   ['Utah'],
   ['Alabama'],
   ['Georgia'],
   ['Florida'],
   ['North Carolina'],
   ['Kentucky'],
   ['North Dakota'],
   ['Montana'],
   ['Oregon'],
   ['Arizona'],
   ['Maine'],
   ['Rhode Island'],
   ['Pennsylvania']],
  ['state',
   'state of birth',
   'state of residence',
   'office location',
   'location']],
 'age': [['32',
   '33',
   '31',
   '29',
   '30',
   '38',
   '63',
   '46',
   '36',
   '47',
   '37',
   '44',
   '54',
   '49',
   '28',
   '48',
   '42',
   '53',
   '66',
   '34',
   '52',
   '39',
   '45',
   '41',
   '40',
   '62',
   '43',
   '59',
   '27',
   '67',
   '50',
   '35',
   '26',
   '25',
   '65',
   '51',
   '58',
   '56',
   '64'],
  [['old', 'years old', 'age of', 'ages of']],
  []],
 'sex': [['male', 'female'],
  [['men', 'males', 'guys', 'dudes', 'gents', 'gentlemen', 'boys'],
   ['women', 'females', 'ladies', 'lady', 'ladys', 'girls', 'gals', 'woman']],
  ['sex', 'gender', 'masculine', 'feminine', 'male person']],
 'maritaldesc': [['married', 'divorced', 'single', 'separated', 'widowed'],
  [['wed',
    'legally married',
    'espoused',
    'joined in holy matrimony',
    'hitched'],
   nan,
   ['unmarried', 'bachelor', 'bachelorette'],
   nan,
   nan],
  ['husbandless',
   'without a partner',
   'unwedded',
   'wifeless',
   'no longer married',
   'without a husband',
   'without a wife',
   'maritaldesc',
   'marital status',
   'spouse',
   'husband',
   'wife']],
 'citizendesc': [['us citizen', 'eligible noncitizen', 'non-citizen'],
  [nan, nan, nan],
  ['immigrant',
   'illegal immigrant',
   'h1 visa',
   'foreigner',
   'foreign',
   'imported',
   'out of country',
   'from abroad',
   'citizenship status',
   'citizenship']],
 'racedesc': [['black or african american',
   'asian',
   'two or more races',
   'white',
   'hispanic',
   'american indian or alaska native'],
  [['black', 'african american', 'african-american'],
   ['from asia'],
   ['multiracial',
    'multi-racial',
    'mixed',
    'mixed race',
    'biracial',
    'interracial'],
   ['caucasian'],
   ['latino'],
   ['native',
    'natives',
    'indians',
    'indian',
    'american indian',
    'alaska native']],
  ['ethnicity',
   'race',
   'racial background',
   'ethnic group',
   'ethnic type',
   'racial indentity',
   'community']],
 'reason_for_termination': [['return to school',
   'another position',
   'unhappy',
   'military',
   'gross misconduct',
   'hours',
   'medical issues',
   'relocation out of area',
   'more money',
   'career change',
   'n/a - has not started yet',
   'retiring',
   'n/a - still employed',
   'attendance',
   'no-call no-show',
   'maternity leave - did not return',
   'performance'],
  [['went back to school',
    'had to go to school again',
    'needed to go back to school',
    'went back to college'],
   ['took on another job',
    'landed a new position',
    'changed positions',
    'got a new position',
    'found a new position'],
   ["wasn't happy",
    "didn't like his job",
    "didn't like her job",
    'hated the job',
    'disliked the job',
    "didn't enjoy the job",
    "didn't like his work",
    "didn't like her work"],
   ['joined the military',
    'went to the military',
    'left for the military',
    'enlisted in the military',
    'was drafted into the military'],
   nan,
   nan,
   ['got sick', 'fell sick', 'medical problems', 'sick'],
   ['was relocated',
    'had to relocated',
    'was assigned to a new location',
    'was assigned to a different location'],
   nan,
   ['changed careers'],
   nan,
   ['retired', 'went into retirement'],
   nan,
   ['poor attendance', 'bad attendance'],
   nan,
   ['did not come back from maternity leave', 'had a kid and dissapeared'],
   ['poor performance', 'performed below expectations']],
  []],
 'employment_status': [['terminated for cause',
   'leave of absence',
   'active',
   'voluntarily terminated',
   'future start'],
  [['fired', 'let go', 'evicted', 'kicked out', 'removed', 'dismissed'],
   ['on absence leave'],
   ['currently employed', 'currently working', 'currently works'],
   ['quit', 'quitted', 'resigned', 'sent in a resignation'],
   ['will start at a future time',
    'will start later',
    'will start some time in the future']],
  ['renounce', 'employment status', 'current job status']],
 'department': [['executive office',
   'admin offices',
   'production',
   'it/is',
   'software engineering',
   'sales'],
  [nan, nan, nan, nan, ['programming', 'coding', 'software development'], nan],
  ['department', 'team', 'group', 'section', 'division', 'sector']],
 'position': [['it manager - infra',
   'cio',
   'sales manager',
   'president & ceo',
   'administrative assistant',
   'database administrator',
   'area sales manager',
   'it director',
   'sr. accountant',
   'it manager - support',
   'production technician ii',
   'network engineer',
   'sr. network engineer',
   'shared services manager',
   'accountant i',
   'it support',
   'software engineering manager',
   'production technician i',
   'director of operations',
   'director of sales',
   'sr. dba',
   'it manager - db',
   'software engineer',
   'production manager'],
  [nan,
   ['chief information officer'],
   nan,
   ['chief executive officer'],
   nan,
   ['db admin', 'db administrator', 'database admin'],
   nan,
   ['director of it'],
   ['senior accountant'],
   nan,
   ['production technician 2', 'production technician two'],
   nan,
   ['senior network engineer'],
   nan,
   ['accountant 1', 'accountant one'],
   ['tech support'],
   nan,
   ['production technician 1', 'production technician one'],
   ['operations director'],
   ['sales director'],
   ['senior database administrator',
    'senior db admin',
    'senior db administrator'],
   nan,
   ['software developer', 'programmer'],
   nan],
  ['title', 'job title', 'role']],
 'manager': [['brandon leblanc',
   'janet king',
   'board directors',
   'simon roup',
   'jennifer zamora',
   'eric dougall',
   'peter monroe',
   'michael albert',
   'elijiah gray',
   'webster butler',
   'amy dunn',
   'ketsia liebig',
   'brannon miller',
   'david stanley',
   'kissy sullivan',
   'kelley spirea',
   'lynn daneault',
   'john smith',
   'debra houlihan',
   'alex sweetwater'],
  [['manager name',
    'manager',
    'incharge',
    'supervisor',
    'mentor',
    'leadership',
    'boss',
    'management',
    'head',
    'lead',
    'chairman',
    'working for',
    'works for',
    'work for',
    'manage',
    'managed by',
    'managing',
    'manages',
    'reports to',
    'report to',
    'reporting to',
    'reporting',
    'working under',
    'is under',
    'leads']],
  []],
 'employee_source': [['information session',
   'company intranet - partner',
   'social networks - facebook twitter etc',
   'newspager/magazine',
   'internet search',
   'billboard',
   'pay per click',
   'on-line web application',
   'glassdoor',
   'professional society',
   'monster.com',
   'diversity job fair',
   'careerbuilder',
   'mbta ads',
   'word of mouth',
   'other',
   'vendor referral',
   'on-campus recruiting',
   'website banner ads',
   'employee referral'],
  [['info session'],
   nan,
   ['social media',
    'social media apps',
    'facebook',
    'instagram',
    'twitter',
    'snapchat',
    'social network'],
   ['newspaper', 'magazine'],
   ['google',
    'bing',
    'yahoo',
    "search engine - google bing yahoo'",
    'search engine'],
   ['poster'],
   ['ppc', 'google ads', 'google ppc', 'ppc google'],
   ['application potal', 'job portal'],
   ['glass door'],
   ['professional group'],
   ['monster'],
   nan,
   nan,
   ['advertisement', 'ads'],
   ['verbal mention'],
   nan,
   ['referred by vendor', 'vendor referred'],
   ['on-campus job fair', 'career fair'],
   nan,
   ['referred by employee']],
  ['how did you learn about this position',
   'how did you find out about this job',
   'how did you find out about this position',
   'how did you learn about this job']],
 'performance_score': [['exceptional',
   'fully meets',
   'n/a- too early to review',
   'pip',
   'needs improvement',
   'exceeds',
   '90-day meets'],
  [['extraordinary'],
   ['up to the mark', 'meet expectations'],
   nan,
   nan,
   nan,
   ['beyond expectations',
    'more than expected',
    'better than expected',
    'higher than excpected'],
   nan],
  ['performance rating', 'performance score']],
 'money': [['pay rate'],
  [['salary',
    'income',
    'pay',
    'earn',
    'earnings',
    'make',
    'dollars',
    '$',
    'paycheck',
    'earns',
    'earning',
    'earners',
    'earner']],
  ['earns', 'makes', 'amount']],
 'comparator': [['more than', 'equals to', 'less than'],
  [['greater than', 'higher than', 'longer', 'over', 'older than'],
   ['is exactly', 'is equal to', 'equates to'],
   ['lower than', 'below', 'under', 'fewer than']],
  []],
 'date_time': [['date of hire', 'date of termination', 'dob'],
  [['start date', 'date of starting employment', 'hiring date'],
   ['end date', 'date of leaving job', 'date of ending employment'],
   ['birthday',
    'birthdate',
    'birth date',
    'date of birth',
    'day of birth',
    'born on',
    'born on the',
    'born in',
    'born after',
    'born before']],
  ['year']],
 'time_interval': [['time_interval'],
  [['yearly',
    'monthly',
    'annually',
    'bi-weekly',
    'hourly',
    'month to month',
    'month-to-month']],
  ["00's",
   "10's",
   "20's",
   "30's",
   "40's",
   "50's",
   "60's",
   "70's",
   "80's",
   "90's",
   '00s',
   '10s',
   '20s',
   '30s',
   '40s',
   '50s',
   '60s',
   '70s',
   '80s',
   '90s',
   'tens',
   'twenties',
   'thirties',
   'forties',
   'fifties',
   'sixties',
   'seventies',
   'eighties',
   'nineties',
   '1900s',
   '1910s',
   '1920s',
   '1930s',
   '1940s',
   '1950s',
   '1960s',
   '1970s',
   '1980s',
   '1990s',
   '2000s',
   '2010s',
   "1900's",
   "1910's",
   "1920's",
   "1930's",
   "1940's",
   "1950's",
   "1960's",
   "1970's",
   "1980's",
   "1990's",
   "2000's",
   "2010's",
   'by the month']],
 'function': [['percent', 'sum', 'average'],
  [['fraction', 'portion', 'proportion', 'percentage', '%'],
   ['total', 'cumulative', 'added up', 'summed up. totalled', 'summed'],
   ['mean', 'typical', 'typically']],
  ['distribution', 'turn over rate', 'pct']],
 'extreme': [['highest', 'lowest'],
  [['top', 'maximum', 'most', 'greatest', 'max'],
   ['least', 'minimum', 'bottom', 'lowest', 'min']],
  []],
 'employment_action': [['hired', 'terminated'],
  [['employed', 'recruited'], ['fired', 'let go']],
  ['joined']]}

In [45]:
for ent in ent_dict:
    print(ent_dict[ent][1])

[nan]
[['Massachussets'], ['Texas'], ['Connecticut'], ['Virginia'], ['Vermony'], ['California'], ['Washington'], ['New Hampshire'], ['New York'], ['Ohio'], ['Indiana'], ['Idaho'], ['Tennessee'], ['Nevada'], ['Colarado'], ['Utah'], ['Alabama'], ['Georgia'], ['Florida'], ['North Carolina'], ['Kentucky'], ['North Dakota'], ['Montana'], ['Oregon'], ['Arizona'], ['Maine'], ['Rhode Island'], ['Pennsylvania']]
[['old', 'years old', 'age of', 'ages of']]
[['men', 'males', 'guys', 'dudes', 'gents', 'gentlemen', 'boys'], ['women', 'females', 'ladies', 'lady', 'ladys', 'girls', 'gals', 'woman']]
[['wed', 'legally married', 'espoused', 'joined in holy matrimony', 'hitched'], nan, ['unmarried', 'bachelor', 'bachelorette'], nan, nan]
[nan, nan, nan]
[['black', 'african american', 'african-american'], ['from asia'], ['multiracial', 'multi-racial', 'mixed', 'mixed race', 'biracial', 'interracial'], ['caucasian'], ['latino'], ['native', 'natives', 'indians', 'indian', 'american indian', 'alaska native']]
[['went back to school', 'had to go to school again', 'needed to go back to school', 'went back to college'], ['took on another job', 'landed a new position', 'changed positions', 'got a new position', 'found a new position'], ["wasn't happy", "didn't like his job", "didn't like her job", 'hated the job', 'disliked the job', "didn't enjoy the job", "didn't like his work", "didn't like her work"], ['joined the military', 'went to the military', 'left for the military', 'enlisted in the military', 'was drafted into the military'], nan, nan, ['got sick', 'fell sick', 'medical problems', 'sick'], ['was relocated', 'had to relocated', 'was assigned to a new location', 'was assigned to a different location'], nan, ['changed careers'], nan, ['retired', 'went into retirement'], nan, ['poor attendance', 'bad attendance'], nan, ['did not come back from maternity leave', 'had a kid and dissapeared'], ['poor performance', 'performed below expectations']]
[['fired', 'let go', 'evicted', 'kicked out', 'removed', 'dismissed'], ['on absence leave'], ['currently employed', 'currently working', 'currently works'], ['quit', 'quitted', 'resigned', 'sent in a resignation'], ['will start at a future time', 'will start later', 'will start some time in the future']]
[nan, nan, nan, nan, ['programming', 'coding', 'software development'], nan]
[nan, ['chief information officer'], nan, ['chief executive officer'], nan, ['db admin', 'db administrator', 'database admin'], nan, ['director of it'], ['senior accountant'], nan, ['production technician 2', 'production technician two'], nan, ['senior network engineer'], nan, ['accountant 1', 'accountant one'], ['tech support'], nan, ['production technician 1', 'production technician one'], ['operations director'], ['sales director'], ['senior database administrator', 'senior db admin', 'senior db administrator'], nan, ['software developer', 'programmer'], nan]
[['manager name', 'manager', 'incharge', 'supervisor', 'mentor', 'leadership', 'boss', 'management', 'head', 'lead', 'chairman', 'working for', 'works for', 'work for', 'manage', 'managed by', 'managing', 'manages', 'reports to', 'report to', 'reporting to', 'reporting', 'working under', 'is under', 'leads']]
[['info session'], nan, ['social media', 'social media apps', 'facebook', 'instagram', 'twitter', 'snapchat', 'social network'], ['newspaper', 'magazine'], ['google', 'bing', 'yahoo', "search engine - google bing yahoo'", 'search engine'], ['poster'], ['ppc', 'google ads', 'google ppc', 'ppc google'], ['application potal', 'job portal'], ['glass door'], ['professional group'], ['monster'], nan, nan, ['advertisement', 'ads'], ['verbal mention'], nan, ['referred by vendor', 'vendor referred'], ['on-campus job fair', 'career fair'], nan, ['referred by employee']]
[['extraordinary'], ['up to the mark', 'meet expectations'], nan, nan, nan, ['beyond expectations', 'more than expected', 'better than expected', 'higher than excpected'], nan]
[['salary', 'income', 'pay', 'earn', 'earnings', 'make', 'dollars', '$', 'paycheck', 'earns', 'earning', 'earners', 'earner']]
[['greater than', 'higher than', 'longer', 'over', 'older than'], ['is exactly', 'is equal to', 'equates to'], ['lower than', 'below', 'under', 'fewer than']]
[['start date', 'date of starting employment', 'hiring date'], ['end date', 'date of leaving job', 'date of ending employment'], ['birthday', 'birthdate', 'birth date', 'date of birth', 'day of birth', 'born on', 'born on the', 'born in', 'born after', 'born before']]
[['yearly', 'monthly', 'annually', 'bi-weekly', 'hourly', 'month to month', 'month-to-month']]
[['fraction', 'portion', 'proportion', 'percentage', '%'], ['total', 'cumulative', 'added up', 'summed up. totalled', 'summed'], ['mean', 'typical', 'typically']]
[['top', 'maximum', 'most', 'greatest', 'max'], ['least', 'minimum', 'bottom', 'lowest', 'min']]
[['employed', 'recruited'], ['fired', 'let go']]

<h4>Labelling Check</h4>

In [13]:
intent_txt = pd.read_csv('HR Manager Schema - intent_master.csv')
intent_txt

,get_info,get_aggregate,get_employees,get_salary,get_salary_aggregate,get_salary_employees,get_date,get_date_range_aggregate,get date_range_employees,get_hierarchy
0,Returns Data,Returns Number,Returns Employees,Returns Salary,Returns Number,Return Employees,Returns Date,Returns Number,Returns Employees,Returns Employees
1,Returns a column information about a specific ...,"Average, total, percentage of a column",Returns a list of employees that meets a colum...,Returns the salary of a specific employee.,"Average, total, percentage specifically relate...","(Returns Employee Name and Salary, Like Get_Em...","Like Get_Info but only for born, hired, fired ...","(Average, Total, Percentage) Like Get_Aggregat...","Like Get_Employees but filtered by Date(Born, ...",(up and down hierarchy employees for all names...
2,What is {nan|name}'s race?,What is the {total|function} number of {us cit...,Give me employees who are {single|maritaldesc},What is {Mia|name}'s pay?,What is the {median|function} {pay|money} of {...,Who makes the most money?,What is the {date of hiring|date_time} for {Mi...,What {percentage|function} of employees were {...,Give me a list of people {hired this year|date...,Who is {Mia|name}'s manager?
3,Is {Michael|name} {married|maritaldesc}?,What {percent|function} of employees {exceeded...,All employees from {MA|state},What is {Mia|name}'s pay rate?,what {percentage|function} of employees make {...,Which employees make more than {$|money}{10|sy...,When did {Amy|name} join the company?,What {percent|function} of employees were {hir...,Tell me about employees who {started in Spring...,Which employees have {Julia|name} as their man...
4,What is {Nan|name}'s official position?,What is the {percentage|function} of new grads...,Which employees have been recently {terminated...,What is the pay rate of {Julia|name}?,What is the {average|function} {pay rate|money}?,Which employee(s) have {lowest|comparator} {in...,How long has {Ivan|name} been with the company?,What {percentage|function} of employees were {...,Which employees were not yet {born|date_time} ...,What is the name of {Julia|name}'s manager?
5,How much does {Mia|name} get {paid|money}?,What is the {average|function} {age|age}?,Which employees are not {US citizens|citizende...,What is {Nan|name}'s pay rate?,What is the {average|function} {pay|money} of ...,Tell me who all are {making|money} {more than|...,When was {Nan|name} {fired|employment_action}?,What {percent|function} of all our employees w...,list the employees who {joined last Monday|dat...,Who is {Michael|name}'s manager?
6,How {old|age} is the manager for the engineeri...,What percent of employees are managers?,Which employees were {let go|employment_action...,How much does {Michael|name} make?,Calculate the {average|function} {pay rate|mon...,Which {software engineers|position} are {paid|...,How long was {Mia|name} working for?,What {percentage|function} of employees were {...,Which employess were {hired|employment_action}...,Who is {John Reeder|name}'s manager?
7,What is {Mia|name}'s employment status?,What's the {average|function} {age of|age} emp...,how many employees work from {California|state},Is {Mia|name} being {paid|money} {$|money}{40k...,{average|function} {pay rate|money} for {women...,who make a {salary|money} {more than|comparato...,When was {Michael|name}'s date of hire?,How many employees were {hired|employment_acti...,"Which employees were {hired after Jan 1, 2019|...",Who is {Mia Brown|name}'s manager?
8,Is {Ivan|name} from out of state?,What {percentage|function} of the employees ar...,Which employees have been {terminated|employme...,Does {Mia|name} get {$|money}{70k|sys_number} ...,What's the {average|function} {pay rate|money}?,For employees {hired|employment_action} {betwe...,What is {Nan|name}'s date of birth?,How many people were based out of {Colarado|st...,Who worked for Cisco for {less than|comparator...,Who is the manager for {Bob|name}
9,Does {Michael|name} still work at Cisco?,What {percentage|function} of employees are {e...,Which employees have been with the company lon...,When we let {Nan|name} go {fired|employment_ac...,What is the {average|function} {pay rate|money...,For employees {hired|employment_action} {betwe...,What year was {Mia|name} hired?,What {percentage|function} of employees have b...,Which employees have been {hired this year|dat...,What is {Mia|name}'s manager's name?
10,What is {Mia|name}'s performance score?,What {percentage|function} of employees are {f...,Which employees have gotten only {positive fee...,{pay rate|money} of {Mia|name},How many employees are paid above {$|money}{20...,Of all employees that {started at the company|...,When did we {fire|employment_action} {Jeff|name}?,How many employees are below the {age of|age} ...,Which employee was {hired within the last mont...,Who reports into {Nan Singh|name}
11,What position is {Julia|name} in?,{Percentage|function} of Employees in departme...,Which employees have a {spouse|maritaldesc}?,how much money does {Mia|name} make?,what number of people {earn|money} {fewer than...,Tell me who earned the {least|extreme} that wa...,How long has {Mia|name} worked here?,How many employees are {under|comparator} {30|...,Which employees have {been with us|date_time} ...,can i have the names of employees who report t...
12,Which department is {Michael|name} in?,What {percentage|function} of employees {meet ...,Which employees {quit working|employment_statu...,What does {Mia|name} {make|money}?,what number of people {earn|money} {fewer than...,Of the employees {hired after 2014|date_time} ...,When was {Mia|name}'s date of hire?,How many employees are {over|comparator} {50|s...,Give me the employees that have {been with us|...,Which employees are under the Manager {Amy|name}?
13,How did {Mia|name} hear about our company?,What {percentage|function} of employees are pa...,Which employees are {activley employed|employm...,How much {money|money} does {Mia|name} bring i...,how many people are {paid|money} {less than|co...,Which workers are {compensated|money} {more th...,What was the {Amy|name}'s date of hire?,How many employees were born in the {year 2009...,I want a list of employees that were {born in|...,who {works for|manager} {Nan Singh|name}
14,Is {Nan|name} {married|maritaldesc}?,Give an estimate {total|function} of the {fema...,Which employees have the {highest|comparator} ...,"{Each year|time_interval}, how much does {Mia|...",How many employees make {6 figure|sys_number} ...,Which employee that {works under|manager} {Sim...,When was {Michael|name} {hired|employment_acti...,How many people have worked here since {2015|d...,Which employees were {born in|date_time} the {...,Tell who is {working under|manager} Mr. {Singh...
15,Why did {Mia|name} get fired?,What {percent|function} of people working here...,Who was {hired|employment_action} based on a {...,What are {Mia|name}'s {earnings|money} {year t...,What is the {total|function} {earnings|money} ...,Tell me the employee that {works for|manager} ...,When was {Mia|name} {hired|employment_action}?,How many people are there under {30|sys_number}?,Fetch me a list of workers that have their {bi...,employee list with {manager|manager} being {Na...
16,Which department does {Mia|name} work for?,What is the {percentage|function} of employees...,Which employees are in the {engineering depart...,What is {Mia|name}'s {annual|time_interval} {s...,How much does the {average|function} employee ...,What are the {yearly|time_interval} {salaries|...,What was {Mia|name}'s {date of hiring|date_time}?,Employees with more than {5 yrs|sys_duration} ...,What are our {top|extreme} {10|sys_number} {ol...,{Nan singh|name} is the {manager|manager} of w...
17,Does {Julia|name}'s {manger|manager} provide h...,Tell me the {percent|function} of employees ar...,Which employees have the {lowest|comparator} p...,What does {Mia|name} {make|money} {monthly|tim...,What is the {average|function} {amount of mone...,Which {Sr. DBA|position} {earns|money} the {mo...,What was the exact date when {Amy|name} {start...,number of people {working since 2016|date_time},Give me the {top|extreme} ten {youngest|age} w...,which employees is {Nan singh|name} the {manag...
18,How old is the {Ivan|name}?,What {fraction|function} of our employees are ...,Which employees are {asian|racedesc}?,How much does {Mia|name} {make|money} {every m...,What is the {total|function} {earnings|money} ...,"Of all the {Production Managers|position}, whi...",Can you tell me how long has {Ivan|name} worke...,{total|function} number of employee that have ...,List of {oldest|age} workers,for which employees is {Nan singh|name} the {s...
19,Is {Nan|name} {actively employed|employment_st...,What is the {percentage|function} of {senior e...,Which employees are {US citizens|citizendesc}?,How much does Cisco {pay|money} {Mia|name} {ea...,How much {money|money} did all the employees {...,Get me the {top|extreme} {ten|sys_number} {ear...,Which date was {Nan|name} {let go|employment_a...,what is the {fraction|function} of employees t...,List of {youngest|age} works,{nan singh|name} is the {manager|manager} for ...
20,What is {Mia|name}'s position?,What {percentage|function} of workers are {old...,Show {married|maritaldesc} employees,How much {salary|money} does {Mia|name} {earn|...,Get me the combined {total|function} incomes f...,I want the {5|sys_number}{%|function} {bottom|...,Give me {Mia|name}'s {hiring date|date_time},have there been any employees that have been {...,{oldest|age} employees list,which of our employees have {nan singh|name} a...
21,What was the reason for {Mia|name}'s termination?,What is the {median|function} {age of|age} emp...,Who is married in {Collaboration Department|de...,Does {Mia|name} {make|money} {more than|compar...,Tell me about the {range|function} of {salarie...,Admin Offices {bottom|extreme} {16|sys_number}...,When {Amy|name} was {hired|employment_action} ...,can you please tell me what {fraction|function...,{youngest|age} employees list,get me a list of all of the employees that are...
22,Where does {Mia|name} live?,What is the {voluntary attrition rate|function...,Which employees are {over|comparator} {30|sys_...,Does {Mia|name} {earn|money} more money than s...,Describe the {salary|money} {range|function} f...,list of {top|extreme} twenty {earners|money} i...,Has {Ivan|name} been working here for {3 years...,what is the {total|function} number of employe...,{15|sys_number} most recently {fired|employmen...,employees that directly {report|manager} to Mr...
23,Where is {Mia|name} from?,What {fraction|function} of {terminations|empl...,Which employee(s) {do not meet|performance_sco...,What is {Mia|name}'s exact {salary|money} in {...,What percent of workers {made|money} below {70...,Who {earns|money} the {most|extreme} in the {p...,What was the date when {Mia|name} was {hired|e...,employees {born|date_time} {before 1994|sys_in...,{fifteen|sys_number} most recently {hired|empl...,who is Ms. {Amy Dunn|name} {reporting|manager} to
24,What is {Hakim|name}'s level in the organization?,What {percentage|function} of employees are {m...,Which employees were {recruited|employment_act...,Tell me about {Mia|name}'s {month to month|tim...,Of all the workers that {started at the compan...,who {makes|money} the {least|extreme} {amount ...,When {Mia|name} {began her employment|date_tim...,i want the {count|function} of employees that ...,Which employees joined the company recently,"Does {Amy Dunn|name} have a {manager|manager},..."
25,What is {Nan Singh|name}'s performance evaluat...,What is the {percentage|function} of {engineer...,Which employees are {citizens|citizendesc}?,Is {50k|sys_number} {more than|comparator} wha...,Employees {hired between 2013 and 2014|date_ti...,Which White employee {earns|money} the {most|e...,The date was what when {Mia|name} {started wor...,{percent|function} of employees {born|date_tim...,Give me a list of employees that were {hired i...,I want to know the name of the {manager|manage...
26,What is {Nan|name}'s last name?,what {proportion|function} of employees were {...,Which employees have a position?,"Does {60,000|sys_number} exceed what {Mia|name...",{Mean|function} {pay|money} of workers {hired ...,who are the company's {top|extreme} {20|sys_nu...,{Mia|name} {start date|date_time},{1980|sys_time} {born|date_time} employees {to...,Give me a list of folks {fired last summer|dat...,{Amy Dunn|name} {manager|manager}
27,Does {Mia|name}'s race affect her indulgence?,What is the {percentage|function} breakdown of...,Which employees are {married|maritaldesc}?,{Mia|name} {Salary|money} {Yearly|time_interval},"Of the employees {born before 1990|date_time},...",give me the {salaries|money} of {interracial|r...,{Mia|name} {fire date|date_time},how many employees were {born|date_time} withi...,Which employees did we {get rid of last fall|d...,{amy dunn|name} {manager|manager} name
28,How well is the employee doing?,What is the {average|function} tenure of emplo...,Which employees are {female|sex}?,{Mia|name} {Salary|money} {Monthly|time_interval},What are workers {born before 1985|date_time} ...,give me the {salaries|money} for all of the em...,"{start date|date_time}, {Mia|name}",what is the number of employees {born|date_tim...,Which employees are {born in|date_time} {May|s...,{manager|manager} name for ms {amy dunn|name}
29,What does {Michael|name} look like?,What {percent|function} of employees are {fema...,Who is our {oldest|age} employee?,{Mia|name} {Salary|money} {Daily|time_interval},What is the {typical|function} {compensation|m...,I want a list with {salaries|money} of employe...,"{fire date|date_time}, {Ivan|name}",NaN,Give me a list of employees that have a {birth...,get me ms. {dunn|name}'s {manager|manager} ful...
...,...,...,...,...,...,...,...,...,...,...
62,tell me what is {Mia|name}'s citizenship status,How many people have worked here since {2015|s...,{divorced|maritaldesc} employees,{Mia|name} {pay|money} info,amount of {money|money} {earned|money} by {fem...,{sales department|department} {salaries|money},when did {Amy|name} officially {join|employmen...,NaN,{singles|maritaldesc} {fired|employment_action...,tell me the {supervisor|manager} that is {repo...
63,is {Mia|name} a {citizen|citizendesc},How many employees are {C-levels|position}?,give me a list of {separated employees|marital...,{Mia|name} {salary|money} amount info,what is the {fraction|function} of {female|sex...,show me the employee {salaries|money} for {fem...,{Nan|name} {firing date|date_time},NaN,{married|maritaldesc} employees {hired|employm...,NaN
64,which branch is {Nan|name} working in,What is the total number of {Black or African ...,employees that are {separated|maritaldesc},Tell me how much {Mia|name} {making|money},i want the {fraction|function} of employees in...,what are the {salaries|money} for {active|empl...,{Amy|name} {date of fire|date_time},NaN,{divorced|maritaldesc} folks that had their em...,NaN
65,why did we {let go|employment_action} of {Nan|...,How many of {Mia Brown|name}'s reports left th...,workers that have been {divorced|maritaldesc},What is {Mia|name} {making|money},what is the {porportion|function} of workers {...,what are the {salaries|money} for employees th...,{Mia|name} {date of employment termination|dat...,NaN,white employees {born|date_time} {after 1990|s...,NaN
66,did we {fire|employment_action} Mr. {Nan|name}...,How many people are there under {30|sys_number}?,employees between the {age of|age} {20|sys_num...,What does {Mia|name} {make|money} on the {Payr...,what is the {lowest|extreme} {pay|money} in th...,show me the {highest|extreme} {earning|money} ...,employment {termination date|date_time} {Amy|n...,NaN,{90's|time_interval} {born|date_time} {white|r...,NaN
67,can you desribe the race of {Nan|name} Singh,how many employees work for the {collab depart...,employees in their {20|sys_number}'s,What is cisco giving {Mia|name} to {pay|money}...,what is the {total|function} {pay|money} in th...,who is the {highest|extreme} {earning|money} {...,{Mia|name} was {fired on which date|date_time},NaN,{asians|racedesc} {born in|date_time} the {80'...,NaN
68,give me {Nan|name}'s race please,How many managers are there?,{20|sys_number} {yr old|age} employees,What is {Mia|name}'s {hourly|time_interval} {s...,how much are all the employees in the {sales d...,{IT support|position} {top|extreme} {earner|mo...,{Mia|name} {termination date|date_time},NaN,find me the {asians|racedesc} {born|date_time}...,NaN
69,how did {Nan|name} hear about us,What are the {M/F|sex} ratios in different dep...,{34|sys_number} {year old|age} employees,What does {Mia|name} {make|money} {on the hour...,how much is the {sales department|department} ...,{IT support|position} {lowest|extreme} {earner...,Was {Mia|name} {fired in between the month of ...,NaN,get me {accountants|position} {born|date_time}...,NaN
70,did {Nan|name} hear about us through {Glassdoo...,How many employees {meet|performance_score} th...,employees {older than|age} {30 years|sys_durat...,{Hourly|time_interval} {pay|money} {Mia|name},get me the {total|function} amount that the {s...,the {lowest|extreme} 10 {earners|money} in {Sa...,tell me the date when {Mia|name} had to {leave...,NaN,who are our {90's|time_interval} {born|date_ti...,NaN
71,NaN,Employees with more than {5 yrs|sys_duration} ...,employees that live in {california|state},{Mia|name} {hourly|time_interval} {pay|money},NaN,NaN,What was {Amy|name}'s official join date at th...,NaN,NaN,NaN
72,NaN,How many employees fall {below expectations|pe...,employees from {MA|state},{Mia|name} {hourly|time_interval} {compensatio...,NaN,NaN,What is the duration of {Ivan|name}'s employme...,NaN,NaN,NaN
73,NaN,How many employees are out of state?,{MA|state} employees,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,NaN,How many employees are between {20|sys_number}...,{MA|state} employees list,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,NaN,How many employees are {older than|comparator}...,give me a list of employes that are based in {...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,NaN,What is the employee's race?,{MA|state} based employees,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,NaN,How many employees live in {California|state}?,employees based in {MA|state},NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,NaN,How many employees are above 35?,Which employees are {managers|position}?,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,NaN,How many employees are from {New York|state}?,employees that are {managers|position},NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,NaN,How many employees were {born in January|date_...,list of {managers|position},NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,NaN,How many {software engineers|position} do we h...,{managers|position} list,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,NaN,How many workers performed {below expectations...,{manager|position} employees,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,NaN,How many {software engineers|position} work fo...,employee {managers|position},NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,NaN,How many employees are named {Ivan|name}?,{managers|position},NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,NaN,When do we most often {hire/fire|employment_st...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,NaN,How many employees are {over|comparator} the {...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,NaN,Number of {Married|maritaldesc} employees,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,NaN,Hiow many employees are in our department?,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,NaN,How many {business analysts|position} are empl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,NaN,How many people are {over|comparator} {21|sys_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,NaN,How many employees work for {Michael Albert|ma...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [121]:
text = intent_txt[intent_txt.columns[2]][10]
text

'Which employees have gotten only {positive feedback|performance_score}?'

In [178]:
get_labels(text)

['{positive feedback|performance_score}']

In [179]:
get_label_kv(get_labels(text))

[['positive feedback'], ['performance_score']]

In [130]:
def get_labels(text):
    chars = list(text)
    start, stop = 0, 0
    labels = []
    for i in range(len(chars)):
        if chars[i] == '{': 
            start = i
        if chars[i] == '}':
            stop = i
            txt = chars[start:(stop + 1)]
            labels.append("".join(chars[start:(stop + 1)]))
    return labels

In [131]:
def get_label_kv(labels):
    k = []
    v = []
    for label in labels:
        k.append(label.split('|')[0].replace("{", ""))
        v.append(label.split('|')[1].replace("}", ""))
    return [k,v]

In [226]:
def label_chk_helper(sentence, ent_dict, labels, col, idx):

    for ent in ent_dict:
        syns = get_synonyms(ent_dict, ent)
        
        for syn in syns:
            if syn in sentence and syn not in labels[0] and syn not in labels[1]: pass
#                 print("POTENTIAL MISSING LABEL")
#                 print("SYNONYM: " + syn)
#                 print("ENTITY: " + ent)
#                 print("SENTENCE: " + sentence)
#                 print("Column: " + col)
#                 print("Index: " + idx)
#                 print("==========================================")

In [230]:
# Check if the Synonyms to Entities Were not Labelled in Training
# param df (dataframe) - Dataframe where each column is an intent and each row has sentence examples
# param ent_dict (dict) - Dictionary that contains entities as keys and synonyms
def label_chk(df, ent_dict):
    for col in df:
        print(col.upper() + "=============================================================")
        idx = 2
        nan = is_nan(df[col][idx])
        while(not nan):
            try:
                nan = is_nan(df[col][idx])
                # Check for Synonyms
                l_dict = {}
                
                sentence = df[col][idx]
                labels = get_labels(sentence)
                labels = get_label_kv(labels)
                label_chk_helper(sentence, ent_dict, labels, col, idx)
                
                if(len(labels[0]) != 0):
                    for ct in range(len(labels[0])):
                        k = labels[0][ct]
                        v = labels[1][ct]
            
                        if k in l_dict:
                            print("MISMATCH " + k)
                            print("SENTENCE: " )
                        else: 
                            l_dict[k] = v

                
                idx += 1
            except Exception as e: 
                #print(e)
                break

In [229]:
label_chk(intent_txt, ent_dict)

GET_INFO=============================================================
GET_AGGREGATE=============================================================
GET_EMPLOYEES=============================================================
GET_SALARY=============================================================
GET_SALARY_AGGREGATE=============================================================
GET_SALARY_EMPLOYEES=============================================================
MISMATCH earning
GET_DATE=============================================================
GET_DATE_RANGE_AGGREGATE=============================================================
GET DATE_RANGE_EMPLOYEES=============================================================
GET_HIERARCHY=============================================================
MISMATCH manager
MISMATCH supervisor

<h4>Generate Gazetteers</h4>

In [ ]:
gen_gazetteers(ent_dict)

<h4>Generate Mapping.json</h4>

In [ ]:
gen_map_json_files(ent_dict)